version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flightmatedb
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx prisma db seed &&
      npm start"
      
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flightmatedb
    ports:
      - "5433:5432" # Change the host port to 5433

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
